version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_ID: your_github_id
        GITHUB_SECRET: your_github_secret
        NEXTAUTH_SECRET: your_nextauth_secret
        GOOGLE_CLIENT_ID: your_google_client_id
        GOOGLE_CLIENT_SECRET: your_google_client_secret
        UPS_CLIENT_ID: your_ups_id
        UPS_CLIENT_SECRET: your_ups_secret
        FEDEX_API_KEY: your_fedex_key
        SHIPPO_API_KEY: your_shippo_key
        DB_USERNAME: postgres
        DB_PASSWORD: password
        DB_DATABASE: app_db
    environment:
      NODE_ENV: production
    secrets:
      - github_id
      - github_secret
      - nextauth_secret
      - client_id
      - client_secret
      - ups_client_id
      - ups_client_secret
      - fedex_api_key
      - shippo_api_key
      - db_username
      - db_password
      - db_database

  caddy:
    image: caddy:latest
    container_name: adapnow-caddy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./public/uploads:/app/public/uploads
    depends_on:
      - frontend
    environment:
      - CADDY_LOG_LEVEL=DEBUG

volumes:
  caddy_data:
  caddy_config:

secrets:
  github_id:
    file: ./secrets/github_id.txt
  github_secret:
    file: ./secrets/github_secret.txt
  nextauth_secret:
    file: ./secrets/nextauth_secret.txt
  client_id:
    file: ./secrets/client_id.txt
  client_secret:
    file: ./secrets/client_secret.txt
  ups_client_id:
    file: ./secrets/ups_client_id.txt
  ups_client_secret:
    file: ./secrets/ups_client_secret.txt
  fedex_api_key:
    file: ./secrets/fedex_api_key.txt
  shippo_api_key:
    file: ./secrets/shippo_api_key.txt
  db_username:
    file: ./secrets/db_username.txt
  db_password:
    file: ./secrets/db_password.txt
  db_database:
    file: ./secrets/db_database.txt
