version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adapnow-frontend
    working_dir: /app
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    secrets:
      - db_password
      - db_username
      - db_database
      - nextauth_secret
      - client_id
      - client_secret
      - ups_client_id
      - ups_client_secret
      - fedex_api_key
      - shippo_api_key
      - github_id
      - github_secret
    environment:
      - CI=true
      - PNPM_SKIP_VERIFY_STORE_INTEGRITY=true
      - PNPM_ALLOW_BUILTIN_SCRIPTS=true
      - NODE_ENV=production
      - DB_HOST=96.29.236.243
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_USERNAME_FILE=/run/secrets/db_username
      - DB_DATABASE_FILE=/run/secrets/db_database
      - NEXTAUTH_SECRET_FILE=/run/secrets/nextauth_secret
      - CLIENT_ID_FILE=/run/secrets/client_id
      - CLIENT_SECRET_FILE=/run/secrets/client_secret
      - UPS_CLIENT_ID_FILE=/run/secrets/ups_client_id
      - UPS_CLIENT_SECRET_FILE=/run/secrets/ups_client_secret
      - FEDEX_API_KEY_FILE=/run/secrets/fedex_api_key
      - SHIPPO_API_KEY_FILE=/run/secrets/shippo_api_key
      - GITHUB_ID_FILE=/run/secrets/github_id
      - GITHUB_SECRET_FILE=/run/secrets/github_secret
    restart: always
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://adapnow-frontend:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  caddy:
    image: caddy:latest
    container_name: adapnow-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
    environment:
      - CADDY_LOG_LEVEL=DEBUG

volumes:
  caddy_data:
  caddy_config:
  - ./public/uploads:/app/public/uploads
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_username:
    file: ../secrets/db_username.txt
  db_database:
    file: ../secrets/db_database.txt
  nextauth_secret:
    file: ../secrets/nextauth_secret.txt
  client_id:
    file: ../secrets/client_id.txt
  client_secret:
    file: ../secrets/client_secret.txt
  ups_client_id:
    file: ../secrets/ups_client_id.txt
  ups_client_secret:
    file: ../secrets/ups_client_secret.txt
  fedex_api_key:
    file: ../secrets/fedex_api_key.txt
  shippo_api_key:
    file: ../secrets/shippo_api_key.txt
  github_id:
    file: ../secrets/github_id.txt
  github_secret:
    file: ../secrets/github_secret.txt
