version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adapnow-frontend
    working_dir: /app
    volumes:
      - ../secrets:/run/secrets:ro
    environment:
      - NODE_ENV=production
      - DB_PASSWORD_FILE=/run/secrets/db_password.txt
      - NEXTAUTH_SECRET_FILE=/run/secrets/nextauth_secret.txt
      - DB_USERNAME_FILE=/run/secrets/db_username.txt
      - DB_DATABASE_FILE=/run/secrets/db_database.txt
      - CLIENT_ID_FILE=/run/secrets/client_id.txt
      - CLIENT_SECRET_FILE=/run/secrets/client_secret.txt
      - UPS_CLIENT_ID_FILE=/run/secrets/ups_client_id.txt
      - UPS_CLIENT_SECRET_FILE=/run/secrets/ups_client_secret.txt
      - FEDEX_API_KEY_FILE=/run/secrets/fedex_api_key.txt
      - SHIPPO_API_KEY_FILE=/run/secrets/shippo_api_key.txt
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mariadb:10.7
    container_name: adapnow-db
    volumes:
      - ./database-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
    restart: always
    secrets:
      - db_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  caddy:
    image: caddy:latest
    container_name: adapnow-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

secrets:
  db_password:
    external: true
  nextauth_secret:
    external: true
  db_username:
    external: true
  db_database:
    external: true
  client_id:
    external: true
  client_secret:
    external: true
  ups_client_id:
    external: true
  ups_client_secret:
    external: true
  fedex_api_key:
    external: true
  shippo_api_key:
    external: true

volumes:
  caddy_data:
  caddy_config:
